repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.2.5
    hooks:
      - id: prettier
        name: prettier‑sh
        additional_dependencies: ["@prettier/plugin-sh"]
        types: [shell]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.4
    hooks:
      - id: shellcheck
        args: ["--severity", "warning"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
