name: "🐞 Bug report"
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: "1. Run `rpcp ...`\n2. ...\n"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: repocopy version
      placeholder: "v0.1.0"
