name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Bats
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.12.0
      - name: Run Bats tests
        run: bats -r tests/bats

  test-powershell:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Pester tests
        shell: pwsh
        run: |
          Invoke-Pester -Path tests/pester -CI
