name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Linux test deps
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y bats jq xclip
      - name: Run Bash test-suite (Bats)
        if: runner.os == 'Linux'
        run: bats tests/bash/rpcp.bats

      - name: Install Windows test deps
        if: runner.os == 'Windows'
        run: |
          choco install bats --version=1.10.0 -y
          choco install jq -y
      - name: Run PowerShell test-suite (Pester)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Install-Module Pester -Force -Scope CurrentUser
          Invoke-Pester -Path tests/powershell -CI -Output Detailed
